name: "Docker Image Build Test & Push"
description: "Scans container images for vulnerabilities with Trivy and pushed image to docker hub"
inputs:
  dockerhub_username:
    description: "Username for image registry"
    required: true
  dockerhub_access_token:
    description: "dockerhub access token"
    required: true
  image_name:
    description: "Name of the image to push"
    required: true
  folder_name:
    description: "Name of the folder containing the Dockerfile"
    required: true
  tag:
    description: "Image tag. Default is latest"
    required: false
    default: "latest"
  


runs:
  using: "composite"
  steps:
    - name: login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_username }}
        password: ${{ inputs.dockerhub_access_token }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    # - name: Build image
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: "${{ inputs.folder_name}}"
    #     tags: '${{ inputs.dockerhub_username }}/${{ inputs.image_name }}:${{ inputs.tag }}'
        # outputs: type=docker,dest=/tmp/myimage.tar

    # - name: Upload artifact
    #   uses: actions/upload-artifact@v3
    #   with:
    #       name: myimage
    #       path: /tmp/myimage.tar
    # - name: Download artifact
    #   uses: actions/download-artifact@v3
    #   with:
    #       name: myimage
    #       path: /tmp/myimage.tar
    - name: docker build image
      shell: bash
      run: |
        # if [ -z "${{ inputs.tag }}" ]
        # then
        #   echo "final_tag=latest" >> $GITHUB_ENV
        # else
        #   echo "final_tag=${{ inputs.tag }}" >> $GITHUB_ENV
        # fi
        # echo $GITHUB_ENV
        
        docker build -t ${{ inputs.dockerhub_username }}/${{ inputs.image_name }}:${{ inputs.tag }} ${{ inputs.folder_name}}
        docker image ls -a 

    - name: Image scanning using Trivy
      id: scan_image
      uses: aquasecurity/trivy-action@0.16.1
      with:
        image-ref: '${{ inputs.dockerhub_username }}/${{ inputs.image_name }}:${{ inputs.tag }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Push image to docker
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && success() }}
      shell: bash
      run: |
        docker push '${{ inputs.dockerhub_username }}/${{ inputs.image_name }}:${{ inputs.tag }}'
       
    # - name: Push image
    #   if: ${{ success() }}
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: "{{defaultContext}}:${{ inputs.folder_name}}"
    #     push: true
    #     tags: '${{ inputs.dockerhub_username }}/${{ inputs.image_name }}:${{ inputs.tag }}'      

        
        